-- ── 042_da_boats.sql ────────────────────────────────────────────────────────
--
-- "Da Boats" — a heritage register of Shetland LK-registered fishing
-- vessels through the years, modelling the physical hull as the canonical
-- identity rather than any single registration number or name (both of
-- which get reused across boats).
--
-- The schema below is the LK Boats Supabase Package generated by Codex
-- (sql/001_schema.sql + 002_indexes.sql + 003_views.sql), pulled into a
-- single OneShetland migration with public-read / admin-write RLS layered
-- on top so the data is safe to expose to the app and read by anyone.
--
-- Seed data (467 vessels, 3,108 names, 3,136 registrations, 369 photo
-- refs, 2,714 raw source records) lives at:
--   supabase/seed-data/da-boats/*.csv
-- Import order is documented in supabase/seed-data/da-boats/README.md
-- (Supabase dashboard → Table Editor → "Import data from CSV" per table).
--
-- Idempotent — safe to re-run.
-- ────────────────────────────────────────────────────────────────────────────

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ══ 1. Schema (verbatim Codex package) ═════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.source_documents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  source_type text NOT NULL,
  publisher text,
  url text,
  accessed_on date,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.source_records (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_document_id uuid NOT NULL REFERENCES public.source_documents(id) ON DELETE RESTRICT,
  record_type text NOT NULL,
  external_ref text,
  source_page text,
  record_date_text text,
  raw_text text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  extraction_notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.media_assets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_document_id uuid NOT NULL REFERENCES public.source_documents(id) ON DELETE RESTRICT,
  source_record_id uuid REFERENCES public.source_records(id) ON DELETE SET NULL,
  asset_type text NOT NULL,
  title text,
  external_ref text,
  image_url text,
  thumbnail_url text,
  page_url text,
  rights_note text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.vessels (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vessel_key text NOT NULL UNIQUE,
  canonical_name text NOT NULL,
  primary_lk_number text,
  built_year integer,
  built_decade text,
  builder text,
  yard_number text,
  hull_material text,
  country_of_build text,
  status text,
  identity_confidence text NOT NULL DEFAULT 'probable'
    CHECK (identity_confidence IN ('confirmed','probable','possible','unmatched','conflict')),
  identity_notes text,
  source_family text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.vessel_source_links (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vessel_id uuid NOT NULL REFERENCES public.vessels(id) ON DELETE CASCADE,
  source_record_id uuid NOT NULL REFERENCES public.source_records(id) ON DELETE CASCADE,
  confidence text NOT NULL
    CHECK (confidence IN ('confirmed','probable','possible','unmatched','conflict')),
  relationship_type text NOT NULL DEFAULT 'evidence_for_vessel',
  notes text,
  UNIQUE (vessel_id, source_record_id, relationship_type)
);

CREATE TABLE IF NOT EXISTS public.vessel_names (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vessel_id uuid NOT NULL REFERENCES public.vessels(id) ON DELETE CASCADE,
  name text NOT NULL,
  normalised_name text NOT NULL,
  start_year integer,
  end_year integer,
  date_text text,
  is_primary boolean NOT NULL DEFAULT false,
  confidence text NOT NULL DEFAULT 'probable'
    CHECK (confidence IN ('confirmed','probable','possible','unmatched','conflict')),
  source_record_id uuid REFERENCES public.source_records(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.registrations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vessel_id uuid NOT NULL REFERENCES public.vessels(id) ON DELETE CASCADE,
  registration text NOT NULL,
  port_mark text,
  registration_number integer,
  start_year integer,
  end_year integer,
  date_text text,
  is_primary boolean NOT NULL DEFAULT false,
  confidence text NOT NULL DEFAULT 'probable'
    CHECK (confidence IN ('confirmed','probable','possible','unmatched','conflict')),
  source_record_id uuid REFERENCES public.source_records(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.owners (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  normalised_name text NOT NULL UNIQUE,
  notes text
);

CREATE TABLE IF NOT EXISTS public.ownership_periods (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vessel_id uuid NOT NULL REFERENCES public.vessels(id) ON DELETE CASCADE,
  owner_id uuid NOT NULL REFERENCES public.owners(id) ON DELETE RESTRICT,
  start_year integer,
  end_year integer,
  date_text text,
  confidence text NOT NULL DEFAULT 'possible'
    CHECK (confidence IN ('confirmed','probable','possible','unmatched','conflict')),
  source_record_id uuid REFERENCES public.source_records(id) ON DELETE SET NULL,
  notes text
);

CREATE TABLE IF NOT EXISTS public.vessel_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vessel_id uuid NOT NULL REFERENCES public.vessels(id) ON DELETE CASCADE,
  event_type text NOT NULL,
  event_year integer,
  event_date_text text,
  description text NOT NULL,
  location text,
  confidence text NOT NULL DEFAULT 'probable'
    CHECK (confidence IN ('confirmed','probable','possible','unmatched','conflict')),
  source_record_id uuid REFERENCES public.source_records(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.measurements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vessel_id uuid NOT NULL REFERENCES public.vessels(id) ON DELETE CASCADE,
  measurement_year integer,
  length_m numeric,
  tonnage numeric,
  tonnage_type text,
  tonnage_text text,
  engine_power_kw numeric,
  capacity_units numeric,
  source_record_id uuid REFERENCES public.source_records(id) ON DELETE SET NULL,
  notes text
);

CREATE TABLE IF NOT EXISTS public.vessel_relationships (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vessel_id uuid NOT NULL REFERENCES public.vessels(id) ON DELETE CASCADE,
  related_vessel_id uuid NOT NULL REFERENCES public.vessels(id) ON DELETE CASCADE,
  relationship_type text NOT NULL,
  confidence text NOT NULL DEFAULT 'possible'
    CHECK (confidence IN ('confirmed','probable','possible','unmatched','conflict')),
  source_record_id uuid REFERENCES public.source_records(id) ON DELETE SET NULL,
  notes text
);

CREATE TABLE IF NOT EXISTS public.vessel_media_links (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vessel_id uuid NOT NULL REFERENCES public.vessels(id) ON DELETE CASCADE,
  media_asset_id uuid NOT NULL REFERENCES public.media_assets(id) ON DELETE CASCADE,
  source_record_id uuid REFERENCES public.source_records(id) ON DELETE SET NULL,
  confidence text NOT NULL DEFAULT 'possible'
    CHECK (confidence IN ('confirmed','probable','possible','unmatched','conflict')),
  notes text,
  UNIQUE (vessel_id, media_asset_id)
);

-- ══ 2. Indexes (verbatim Codex package) ════════════════════════════════════

CREATE INDEX IF NOT EXISTS idx_source_records_document   ON public.source_records(source_document_id);
CREATE INDEX IF NOT EXISTS idx_source_records_type       ON public.source_records(record_type);
CREATE INDEX IF NOT EXISTS idx_source_records_payload_gin
  ON public.source_records USING GIN(payload);

CREATE INDEX IF NOT EXISTS idx_media_assets_source_document ON public.media_assets(source_document_id);
CREATE INDEX IF NOT EXISTS idx_media_assets_source_record   ON public.media_assets(source_record_id);
CREATE INDEX IF NOT EXISTS idx_media_assets_type            ON public.media_assets(asset_type);
CREATE INDEX IF NOT EXISTS idx_media_assets_payload_gin
  ON public.media_assets USING GIN(payload);

CREATE INDEX IF NOT EXISTS idx_vessels_name_trgm
  ON public.vessels USING GIN(canonical_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_vessels_lk         ON public.vessels(primary_lk_number);
CREATE INDEX IF NOT EXISTS idx_vessels_built_year ON public.vessels(built_year);

CREATE INDEX IF NOT EXISTS idx_vessel_source_links_vessel ON public.vessel_source_links(vessel_id);
CREATE INDEX IF NOT EXISTS idx_vessel_source_links_record ON public.vessel_source_links(source_record_id);

CREATE INDEX IF NOT EXISTS idx_vessel_names_vessel        ON public.vessel_names(vessel_id);
CREATE INDEX IF NOT EXISTS idx_vessel_names_name_trgm
  ON public.vessel_names USING GIN(name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_vessel_names_normalised    ON public.vessel_names(normalised_name);

CREATE INDEX IF NOT EXISTS idx_registrations_vessel       ON public.registrations(vessel_id);
CREATE INDEX IF NOT EXISTS idx_registrations_registration ON public.registrations(registration);
CREATE INDEX IF NOT EXISTS idx_registrations_port_number
  ON public.registrations(port_mark, registration_number);

CREATE INDEX IF NOT EXISTS idx_events_vessel ON public.vessel_events(vessel_id);
CREATE INDEX IF NOT EXISTS idx_events_year   ON public.vessel_events(event_year);
CREATE INDEX IF NOT EXISTS idx_events_type   ON public.vessel_events(event_type);

CREATE INDEX IF NOT EXISTS idx_measurements_vessel      ON public.measurements(vessel_id);
CREATE INDEX IF NOT EXISTS idx_ownership_vessel         ON public.ownership_periods(vessel_id);
CREATE INDEX IF NOT EXISTS idx_ownership_owner          ON public.ownership_periods(owner_id);
CREATE INDEX IF NOT EXISTS idx_vessel_media_links_vessel ON public.vessel_media_links(vessel_id);
CREATE INDEX IF NOT EXISTS idx_vessel_media_links_asset  ON public.vessel_media_links(media_asset_id);

-- ══ 3. Views (verbatim Codex package) ══════════════════════════════════════

CREATE OR REPLACE VIEW public.vessel_timeline AS
SELECT
  e.vessel_id,
  v.canonical_name,
  e.event_year AS year,
  e.event_date_text AS date_text,
  e.event_type AS item_type,
  e.description,
  e.confidence,
  e.source_record_id
FROM public.vessel_events e
JOIN public.vessels v ON v.id = e.vessel_id
UNION ALL
SELECT
  r.vessel_id,
  v.canonical_name,
  COALESCE(r.start_year, r.end_year) AS year,
  r.date_text,
  'registration' AS item_type,
  'Registration: ' || r.registration AS description,
  r.confidence,
  r.source_record_id
FROM public.registrations r
JOIN public.vessels v ON v.id = r.vessel_id
UNION ALL
SELECT
  n.vessel_id,
  v.canonical_name,
  COALESCE(n.start_year, n.end_year) AS year,
  n.date_text,
  'name' AS item_type,
  'Name: ' || n.name AS description,
  n.confidence,
  n.source_record_id
FROM public.vessel_names n
JOIN public.vessels v ON v.id = n.vessel_id;

CREATE OR REPLACE VIEW public.vessel_search AS
SELECT
  v.id,
  v.canonical_name,
  v.primary_lk_number,
  v.built_year,
  v.builder,
  v.hull_material,
  v.status,
  v.identity_confidence,
  string_agg(DISTINCT n.name, ', ' ORDER BY n.name)         AS all_names,
  string_agg(DISTINCT r.registration, ', ' ORDER BY r.registration) AS all_registrations,
  count(DISTINCT l.source_record_id)                       AS source_record_count,
  count(DISTINCT ml.media_asset_id)                        AS media_asset_count
FROM public.vessels v
LEFT JOIN public.vessel_names         n  ON n.vessel_id  = v.id
LEFT JOIN public.registrations        r  ON r.vessel_id  = v.id
LEFT JOIN public.vessel_source_links  l  ON l.vessel_id  = v.id
LEFT JOIN public.vessel_media_links   ml ON ml.vessel_id = v.id
GROUP BY
  v.id, v.canonical_name, v.primary_lk_number, v.built_year,
  v.builder, v.hull_material, v.status, v.identity_confidence;

-- ══ 4. RLS — public read, admin write ══════════════════════════════════════
--
-- Heritage data; the whole point is for anyone to browse it. Reads are
-- open to anonymous + authenticated. Writes are gated to admins (we can
-- relax to moderator later if curation volume justifies it).

ALTER TABLE public.source_documents       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.source_records         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_assets           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vessels                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vessel_source_links    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vessel_names           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.registrations          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.owners                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ownership_periods      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vessel_events          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.measurements           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vessel_relationships   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vessel_media_links     ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  t text;
  tables text[] := ARRAY[
    'source_documents','source_records','media_assets',
    'vessels','vessel_source_links','vessel_names','registrations',
    'owners','ownership_periods','vessel_events','measurements',
    'vessel_relationships','vessel_media_links'
  ];
BEGIN
  FOREACH t IN ARRAY tables LOOP
    EXECUTE format('DROP POLICY IF EXISTS "da_boats public read"  ON public.%I', t);
    EXECUTE format('DROP POLICY IF EXISTS "da_boats admin write" ON public.%I', t);
    EXECUTE format('DROP POLICY IF EXISTS "da_boats admin update" ON public.%I', t);
    EXECUTE format('DROP POLICY IF EXISTS "da_boats admin delete" ON public.%I', t);

    EXECUTE format($f$
      CREATE POLICY "da_boats public read"
        ON public.%I FOR SELECT
        USING (true);
    $f$, t);

    EXECUTE format($f$
      CREATE POLICY "da_boats admin write"
        ON public.%I FOR INSERT
        WITH CHECK (
          EXISTS (SELECT 1 FROM public.profiles p
                   WHERE p.id = auth.uid() AND p.role IN ('admin','moderator'))
        );
    $f$, t);

    EXECUTE format($f$
      CREATE POLICY "da_boats admin update"
        ON public.%I FOR UPDATE
        USING (
          EXISTS (SELECT 1 FROM public.profiles p
                   WHERE p.id = auth.uid() AND p.role IN ('admin','moderator'))
        );
    $f$, t);

    EXECUTE format($f$
      CREATE POLICY "da_boats admin delete"
        ON public.%I FOR DELETE
        USING (
          EXISTS (SELECT 1 FROM public.profiles p
                   WHERE p.id = auth.uid() AND p.role = 'admin')
        );
    $f$, t);
  END LOOP;
END $$;

GRANT SELECT ON public.vessel_timeline TO anon, authenticated;
GRANT SELECT ON public.vessel_search   TO anon, authenticated;
