/**
 * launch-invitation-email.ts — render + check the launch-partner invitation email INSIDE the Edge Function.
 *
 * The web app owns the editable template and the Admin preview (oneshetland-web: lib/launch-partners/email.ts). THIS
 * copy is the one that actually sends, so the function never has to trust rendered HTML coming from a browser: it takes
 * the SAVED subject/opening/body from the database and renders them itself.
 *
 * It is a verbatim copy of the web renderer's rendering + checking code (pure, no imports). Drift between the two is
 * caught by golden test vectors that both repos run (launch-invitation-email.golden.json, identical in each).
 * Do not edit this file by hand without regenerating the golden vectors and the web copy.
 */

export const TOKEN_OPENING = "{{PERSONALISED_OPENING}}";
export const TOKEN_CTA = "{{INVITATION_CTA}}";
export const TOKEN_BUSINESS = "{{BUSINESS_NAME}}";
/** The token older drafts used for the link. Still understood (treated as the call to action). */
export const LINK_PLACEHOLDER = "{{INVITATION_LINK}}";

export const CTA_LABEL = "View your private preview →";
export const CTA_FALLBACK_LINE = "If the button does not work, copy and paste this link:";
export const CTA_TEXT_LABEL = "View your private preview:";
export const NO_INVITATION_TITLE = "Invitation not generated yet";
export const NO_INVITATION_NOTE = "The “View your private preview →” button, and a copy-and-paste link beneath it, are inserted here when you generate the invitation.";

export interface EmailDraft { subject: string; opening: string; body: string }

/** The clear prompt left where a researched opening does not exist. Sending is refused while it remains. */
export const OPENING_PROMPT_START = "[Your short personal opening";
export const openingPrompt = (name: string): string => `${OPENING_PROMPT_START} — why you chose ${name}, in your own words. Replace this line before sending.]`;
export const isOpeningPrompt = (s: string | null | undefined): boolean => !!s && s.includes(OPENING_PROMPT_START);


/* ── rendering ─────────────────────────────────────────────────────────── */

const esc = (s: string): string => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");

/** Only a plain https (or, for local review, http) address may become a link. Anything else is not rendered as one. */
export const isLinkable = (u: string | null | undefined): u is string => !!u && /^https?:\/\/[^\s<>"']+$/.test(u);

/**
 * The quiet company disclosure and opt-out lines. The RENDERER appends them to EVERY outreach email — they are not part of the editable draft, so an
 * edit (or an older saved draft) can never leave them out. Who is writing (the registered company, its place of registration, number and registered
 * office, as the Companies Act asks of business emails) and a plain, human way to say no: a reply to this email (the reply goes to a monitored mailbox,
 * and an administrator records the request, which stops further outreach for good). Deliberately small and quiet: no logo, no link, no tracking,
 * no marketing footer, nothing promotional.
 *
 * SOURCE OF THE PARTICULARS (checked 7 Oct 2026, not guessed): the Companies House public record for company 15480428 — registered name
 * DARREN FULLERTON CONSULTANCY LTD, registered office 155a Tottenham Lane, London, N8 9BT, England and Wales, status Active — which agrees with the
 * company's own settings (dfc-control: company_settings), the statutory footer printed on its invoices, and its purchase orders. The registered
 * office is the London address; the Burra address is a TRADING address and is deliberately not used here.
 */
export const OUTREACH_COMPANY_NAME = "Darren Fullerton Consultancy Ltd";
export const OUTREACH_IDENTITY = `OneShetland is operated by ${OUTREACH_COMPANY_NAME}.`;
export const OUTREACH_REGISTRATION = "Registered in England and Wales · Company No. 15480428";
export const OUTREACH_OFFICE = "Registered office: 155A Tottenham Lane, London, N8 9BT";
export const OUTREACH_CONTACT = "hello@oneshetland.com";
export const OUTREACH_OPT_OUT = "If you’d rather not receive another Launch Partner invitation from us, just reply and let us know.";

/**
 * HOW LONG A PRIVATE INVITATION LASTS — the ONE canonical default, in days. The Admin screen's "Valid for" box, the server action and the
 * database function (admin_issue_launch_invite) all use it; the email states it. (An administrator may choose another length when issuing; the
 * email then states that invitation's real expiry date, so it can never be stale.) It was 30 in Admin and the action but 45 in the database.
 */
export const INVITE_DEFAULT_DAYS = 30;

const expiryDay = (iso: string): string => new Intl.DateTimeFormat("en-GB", { timeZone: "Europe/London", day: "numeric", month: "long", year: "numeric" }).format(new Date(iso));
/**
 * The one quiet line about expiry, added by the RENDERER next to the private link (so a draft can neither omit nor falsify it). With the
 * invitation's real expiry it names the date; before an invitation exists (a draft preview) it names the default length.
 */
export const expiryLine = (expiresAt?: string | null): string =>
  expiresAt && Number.isFinite(Date.parse(expiresAt)) ? `Your private invitation link is available until ${expiryDay(expiresAt)}.` : `Your private invitation link is available for ${INVITE_DEFAULT_DAYS} days.`;

export interface RenderInput {
  subject: string;
  body: string;
  opening?: string | null;
  businessName?: string | null;
  /** The real private link — present only right after Darren generates the invitation, and only in memory. */
  invitationUrl?: string | null;
  /** A stand-in shown when an invitation exists but its link is no longer available (it is shown once). Preview only. */
  maskedUrl?: string | null;
  /** When the invitation expires (ISO). Read from the database, never from the draft. Absent only for a preview before the invitation exists. */
  invitationExpiresAt?: string | null;
}

export interface RenderedEmail {
  subject: string;
  text: string;
  html: string;
  /** True when the real link was inserted (so this is the email as the recipient receives it). */
  hasInvitation: boolean;
}

function expand(body: string, i: RenderInput): string {
  const opening = (i.opening ?? "").trim();
  let out = body.split(TOKEN_BUSINESS).join(i.businessName ?? "");
  out = out.split(TOKEN_OPENING).join(opening);
  // The call-to-action token is left for the caller, which renders it differently for text and HTML.
  return out;
}

const ctaText = (url: string | null, masked: string | null, expiresAt?: string | null): string =>
  (url ? `${CTA_TEXT_LABEL} ${url}` : masked ? `${CTA_TEXT_LABEL} ${masked}` : `[${NO_INVITATION_TITLE} — the link is inserted here when you generate the invitation.]`) + `\n${expiryLine(expiresAt)}`;

const outreachFooterText = (): string =>
  `--\n${OUTREACH_IDENTITY}\n${OUTREACH_REGISTRATION}\n${OUTREACH_OFFICE}\n${OUTREACH_CONTACT}\n\n${OUTREACH_OPT_OUT}\n`;
const outreachFooterHtml = (): string =>
  `<div style="margin:22px 0 8px;padding-top:14px;border-top:1px solid #ece5d6">` +
  `<p style="margin:0 0 8px;font-size:12px;line-height:1.55;color:#6b7280">${esc(OUTREACH_IDENTITY)}<br>${esc(OUTREACH_REGISTRATION)}<br>${esc(OUTREACH_OFFICE)}<br>${esc(OUTREACH_CONTACT)}</p>` +
  `<p style="margin:0;font-size:12px;line-height:1.55;color:#6b7280">${esc(OUTREACH_OPT_OUT)}</p></div>`;

export function renderInvitationEmail(i: RenderInput): RenderedEmail {
  const url = isLinkable(i.invitationUrl) ? i.invitationUrl : null;
  const masked = !url && i.maskedUrl ? i.maskedUrl : null;
  const base = expand(i.body, i);
  const cta = ctaText(url, masked, i.invitationExpiresAt);
  const body = base.split(TOKEN_CTA).join(cta).split(LINK_PLACEHOLDER).join(cta);
  const text = `${body.replace(/\s+$/, "")}\n\n${outreachFooterText()}`;

  const blocks = base.split(/\n{2,}/).map((b) => b.trim()).filter(Boolean);
  const p = "margin:0 0 16px;font-size:16px;line-height:1.55;color:#14222c";
  const html = blocks.map((b) => {
    if (b === TOKEN_CTA || b === LINK_PLACEHOLDER) return ctaHtml(url, masked, i.invitationExpiresAt);
    const lines = b.split("\n");
    if (lines.every((l) => l.startsWith("• "))) {
      return `<ul style="margin:0 0 16px;padding-left:22px;font-size:16px;line-height:1.55;color:#14222c">${lines.map((l) => `<li style="margin:0 0 6px">${esc(l.slice(2))}</li>`).join("")}</ul>`;
    }
    return `<p style="${p}">${lines.map(esc).join("<br>")}</p>`;
  }).join("\n");

  const doc = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><meta name="supported-color-schemes" content="light"><title>${esc(i.subject)}</title></head>` +
    `<body style="margin:0;padding:24px 12px;background:#fbf8f2;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif">` +
    `<div style="max-width:560px;margin:0 auto;background:#ffffff;border:1px solid #ece5d6;border-radius:14px;padding:22px 28px 12px">${brandHeader()}${html}${outreachFooterHtml()}</div></body></html>`;
  return { subject: i.subject, text, html: doc, hasInvitation: !!url };
}

/**
 * The OneShetland mark and name, exactly as the live site header shows them (mark + "OneShetland" in navy). The mark is the
 * site's own logo-mark-keyed.png, resized to 120px for email (public/brand/email/logo-mark-120.png) — same artwork, a fraction
 * of the weight. It is a plain image on our own domain: no link, no query string, no tracking pixel. The name beside it is real
 * text, so the header still reads correctly when a client blocks images.
 */
export const EMAIL_LOGO_URL = "https://oneshetland.com/brand/email/logo-mark-120.png";
function brandHeader(): string {
  return `<table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="margin:0 0 22px;border-bottom:1px solid #ece5d6"><tr>` +
    `<td width="40" style="padding:0 0 14px;width:40px;vertical-align:middle"><img src="${EMAIL_LOGO_URL}" width="40" height="40" alt="OneShetland" style="display:block;width:40px;height:40px;border:0;outline:none"></td>` +
    `<td style="padding:0 0 14px 10px;vertical-align:middle;font-family:Georgia,'Times New Roman',serif;font-size:20px;line-height:24px;font-weight:600;letter-spacing:-0.2px;color:#032f4c">OneShetland</td>` +
    `</tr></table>`;
}

function ctaHtml(url: string | null, masked: string | null, expiresAt?: string | null): string {
  const expiry = `<p style="margin:0 0 20px;font-size:13px;line-height:1.5;color:#6b7280">${esc(expiryLine(expiresAt))}</p>`;
  if (!url && !masked) {
    return `<div style="margin:0 0 8px;padding:14px 16px;border:2px dashed #d8cfbd;border-radius:12px;background:#fbf8f2;color:#3a4754;font-size:14px;line-height:1.5"><strong style="color:#14222c">${esc(NO_INVITATION_TITLE)}</strong><br>${esc(NO_INVITATION_NOTE)}</div>` + expiry;
  }
  const shown = url ?? masked!;
  const href = url ? esc(url) : "#";
  return `<table role="presentation" cellspacing="0" cellpadding="0" border="0" style="margin:4px 0 8px"><tr><td style="border-radius:999px;background:#032f4c"><a href="${href}" style="display:inline-block;padding:14px 26px;font-size:16px;font-weight:700;color:#ffffff;text-decoration:none;border-radius:999px">${esc(CTA_LABEL)}</a></td></tr></table>` +
    `<p style="margin:0 0 6px;font-size:13px;line-height:1.5;color:#6b7280">${esc(CTA_FALLBACK_LINE)}<br><span style="word-break:break-all;color:#3a4754">${esc(shown)}</span></p>` + expiry;
}

/* ── readiness ─────────────────────────────────────────────────────────── */

export interface EmailCheck { ok: boolean; problems: string[] }

/** Is the SAVED draft fit to send? (Whether the invitation exists is a separate gate.) */
export function checkEmail(e: { subject?: string | null; body?: string | null; opening?: string | null; contactEmail?: string | null }): EmailCheck {
  const problems: string[] = [];
  if (!e.subject?.trim()) problems.push("Add a subject.");
  if (!e.body?.trim()) problems.push("Write the message.");
  else {
    if (!e.body.includes(TOKEN_CTA) && !e.body.includes(LINK_PLACEHOLDER)) problems.push(`The message needs ${TOKEN_CTA} where the button and link go.`);
    if (e.body.includes(TOKEN_OPENING) && !e.opening?.trim()) problems.push("Write the personalised opening.");
  }
  if (isOpeningPrompt(e.opening) || isOpeningPrompt(e.body)) problems.push("Replace the personalised-opening prompt with your own line.");
  // A real link must never be saved into a draft: it would sit in the database in the clear.
  const secret = /[?&]invite=[A-Za-z0-9_-]{20,}/;
  if (secret.test(e.body ?? "") || secret.test(e.opening ?? "") || /\b[0-9a-f]{64}\b/.test(`${e.body ?? ""} ${e.opening ?? ""}`)) problems.push("The draft contains what looks like a real invitation link. Leave the call-to-action token; the link is inserted when you generate the invitation.");
  if (!e.contactEmail?.trim()) problems.push("Add the contact's email address.");
  else if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(e.contactEmail.trim())) problems.push("That email address doesn't look right.");
  return { ok: problems.length === 0, problems };
}

