/**
 * purchase-attempt.ts — the parts of "one purchase attempt, one order / gift" that create-product-order-intent and
 * create-gift-intent share.
 *
 * THE MODEL
 *
 * The client mints ONE `client_request_id` per deliberate purchase (checkout-attempt.ts on both clients) and sends it with every
 * request for that purchase, including retries. The server turns it into a row through an atomic claim-or-replay SQL function
 * (claim_product_order / claim_gift_purchase) keyed on (authenticated user, id), so the id can never reach anyone else's attempt.
 *
 * The id is an idempotency token ONLY. It is never a Stripe key and never part of one: the Stripe idempotency key is derived
 * server-side from the row the claim returned (`product-order-<order id>`, `gift-<gift id>`), and that row id is generated by the
 * database. Whatever a client sends, the most it can do is name its own attempt.
 *
 * Because the row is stable per attempt, that row-derived key is finally stable too — which is what makes a retry return the
 * ORIGINAL PaymentIntent instead of creating another.
 */

export const STRIPE_API_VERSION = '2023-10-16';

/** null when the id is acceptable; otherwise why not. 8–100 characters, the same bounds the database enforces. */
export function attemptIdProblem(raw: unknown): string | null {
  if (typeof raw !== 'string') return 'client_request_id required';
  const s = raw.trim();
  if (s.length === 0) return 'client_request_id required';
  if (raw.length < 8 || raw.length > 100) return 'client_request_id must be 8-100 characters';
  return null;
}

export type PayMode = 'wallet' | 'card_form' | 'card_saved';

/** How this attempt pays. Fixed at claim time; a repeat that asks for something else is refused, not honoured. */
export function payModeFor(opts: { wallet: boolean; savedCard: boolean }): PayMode {
  return opts.wallet ? 'wallet' : opts.savedCard ? 'card_saved' : 'card_form';
}

/** A response the handler should return for a claim the database refused, or null if it is something else. */
export function mapClaimError(message: string | undefined | null): { status: number; body: Record<string, unknown> } | null {
  const m = String(message ?? '');
  if (m.startsWith('IDEMPOTENCY_CONFLICT')) {
    return { status: 409, body: { error: 'That checkout no longer matches what you are buying. Please start the checkout again.', code: 'idempotency_conflict' } };
  }
  const sold = m.match(/^SOLD_OUT: (.*)$/);
  if (sold) return { status: 409, body: { error: `${sold[1]} sold out while you were browsing — sorry!`, code: 'sold_out' } };
  return null;
}

export const EXPIRED_BODY = { error: 'This checkout has expired — please start it again.', code: 'checkout_expired' } as const;
export const IN_PROGRESS_BODY = { error: 'Your payment is already being processed — give it a moment, then check your orders.', code: 'in_progress' } as const;

export class StripeError extends Error {
  code?: string; status: number; type?: string;
  constructor(message: string, status: number, code?: string, type?: string) { super(message); this.status = status; this.code = code; this.type = type; }
}

/**
 * A card the issuer refused. Stripe stores the FIRST answer to an idempotency key — errors included — so asking again under the
 * same key returns the same refusal. It is therefore a final outcome for the attempt, not a transient failure to retry.
 */
export function isCardDecline(e: unknown): boolean {
  return e instanceof StripeError && (e.type === 'card_error' || e.status === 402);
}

const stripeHeaders = (extra: Record<string, string> = {}): Record<string, string> => ({
  'Authorization': `Bearer ${Deno.env.get('STRIPE_SECRET_KEY') ?? ''}`,
  'Stripe-Version': STRIPE_API_VERSION,
  ...extra,
});
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

/**
 * Create a PaymentIntent under a server-derived idempotency key.
 *
 * Two requests for the same attempt reach Stripe with the SAME key, so Stripe returns the same object to both. While the first
 * is still in flight Stripe answers the second with `idempotency_key_in_use` (HTTP 409); that is not a failure, it means "the
 * other one is already making it", so we wait briefly and ask again and receive the original.
 */
export async function createPaymentIntentOnce(params: Record<string, string>, idempotencyKey: string): Promise<Record<string, any>> {
  if (!idempotencyKey) throw new Error('createPaymentIntentOnce: an idempotency key is required');
  let last: StripeError | null = null;
  for (let attempt = 0; attempt < 4; attempt++) {
    const res = await fetch('https://api.stripe.com/v1/payment_intents', {
      method: 'POST',
      headers: stripeHeaders({ 'Content-Type': 'application/x-www-form-urlencoded', 'Idempotency-Key': idempotencyKey }),
      body: new URLSearchParams(params),
    });
    const json = await res.json();
    if (res.ok) return json;
    last = new StripeError(json?.error?.message ?? `Stripe PaymentIntent failed (HTTP ${res.status})`, res.status, json?.error?.code, json?.error?.type);
    if (last.code === 'idempotency_key_in_use') { await sleep(300 * (attempt + 1)); continue; }
    throw last;
  }
  throw last ?? new Error('Stripe PaymentIntent failed');
}

/** Read an existing PaymentIntent (a replay resumes the payment it already started; it never starts another). */
export async function retrievePaymentIntent(id: string): Promise<Record<string, any>> {
  const res = await fetch(`https://api.stripe.com/v1/payment_intents/${encodeURIComponent(id)}`, { headers: stripeHeaders() });
  const json = await res.json();
  if (!res.ok) throw new StripeError(json?.error?.message ?? `Stripe PaymentIntent retrieve failed (HTTP ${res.status})`, res.status, json?.error?.code);
  return json;
}
