-- import_events.sql
-- Imports the 52 events from the WordPress "The Events Calendar" export into
-- public.events. Run in the Supabase SQL editor.
--
--  • Times are wrapped in `AT TIME ZONE 'Europe/London'` so they store the
--    correct UTC instant (DST-accurate — summer gigs aren't an hour out).
--  • &amp; decoded to & in titles/categories.
--  • status = 'published' so they appear immediately (the table trigger sets
--    is_hidden = false to match).
--  • Idempotent: re-running won't duplicate (skips rows whose title+starts_at
--    already exist).

insert into public.events
  (title, description, starts_at, ends_at, venue, category, cover_url, price_text, status)
select
  v.title, v.description, v.starts_at, v.ends_at, v.venue, v.category, v.cover_url, v.price_text, 'published'
from (values
  ($$Mareel Film Quiz$$, $$Mareel Film Quiz at Mareel - Music, Cinema and Education Venue promises a lively night of questions, laughter and friendly competition – perfect for gathering a team and testing your knowledge.$$, timestamp '2026-03-12 19:30:00' at time zone 'Europe/London', timestamp '2026-03-12 22:30:00' at time zone 'Europe/London', $$Mareel - Music -  Cinema and Education Venue$$, $$Cinema$$, $$https://oneshetland.com/wp-content/uploads/2026/03/mareel-film-quiz.webp$$, NULL),
  ($$South Mainland Up Helly Aa (SMUHA)$$, $$South Mainland Up Helly Aa (SMUHA) — part of the lively calendar of community events across Shetland.$$, timestamp '2026-03-13 03:00:00' at time zone 'Europe/London', timestamp '2026-03-14 02:59:59' at time zone 'Europe/London', NULL, $$Heritage & Culture$$, $$https://oneshetland.com/wp-content/uploads/2026/03/south-mainland-up-helly-aa-smuha.jpg$$, NULL),
  ($$SMUHA Hop Day$$, $$SMUHA Hop Day at Ness Boating Club Caravan & Motorhome Site — part of the SMUHA celebrations.$$, timestamp '2026-03-14 13:00:00' at time zone 'Europe/London', timestamp '2026-03-14 23:45:00' at time zone 'Europe/London', $$Ness Boating Club$$, $$Food & Drink$$, $$https://oneshetland.com/wp-content/uploads/2026/03/smuha-hop-day.webp$$, NULL),
  ($$SMUHA Hop – The Dead Pans$$, $$SMUHA Hop – The Dead Pans at Cunningsburgh Hall.$$, timestamp '2026-03-14 21:00:00' at time zone 'Europe/London', timestamp '2026-03-14 23:45:00' at time zone 'Europe/London', $$Cunningsburgh Hall$$, $$Festivals & Celebrations$$, $$https://oneshetland.com/wp-content/uploads/2026/03/south-mainland-up-helly-aa-smuha-hop-night.webp$$, NULL),
  ($$Craft Night$$, $$Craft Night at Skeld Public Hall.$$, timestamp '2026-03-19 19:00:00' at time zone 'Europe/London', timestamp '2026-03-19 21:00:00' at time zone 'Europe/London', $$Skeld Public Hall$$, $$Art & Exhibitions$$, $$https://oneshetland.com/wp-content/uploads/2026/03/craft-night.avif$$, NULL),
  ($$Delting Up Helly Aa$$, $$Delting Up Helly Aa at Brae, Shetland.$$, timestamp '2026-03-20 03:00:00' at time zone 'Europe/London', timestamp '2026-03-21 02:59:59' at time zone 'Europe/London', $$Brae$$, $$Heritage & Culture$$, $$https://oneshetland.com/wp-content/uploads/2026/03/delting-up-helly-aa-1.jpg$$, NULL),
  ($$Neil Cowley Trio$$, $$Neil Cowley Trio at Mareel.$$, timestamp '2026-03-21 19:30:00' at time zone 'Europe/London', timestamp '2026-03-21 21:30:00' at time zone 'Europe/London', $$Mareel - Music -  Cinema and Education Venue$$, $$Music & Gigs$$, $$https://oneshetland.com/wp-content/uploads/2026/03/neil-cowley-trio.webp$$, NULL),
  ($$Waas Got Talent$$, $$Waas Got Talent at Walls Public Hall showcases local performers and hidden talents.$$, timestamp '2026-03-22 19:00:00' at time zone 'Europe/London', timestamp '2026-03-22 23:45:00' at time zone 'Europe/London', $$Walls Public Hall$$, $$Comedy$$, $$https://oneshetland.com/wp-content/uploads/2026/03/waas-got-talent.png$$, NULL),
  ($$Ken Ludwig’s – MORIARTY$$, $$Ken Ludwig’s – MORIARTY at Mareel.$$, timestamp '2026-03-24 19:00:00' at time zone 'Europe/London', timestamp '2026-03-24 21:30:00' at time zone 'Europe/London', $$Mareel - Music -  Cinema and Education Venue$$, $$Theatre$$, $$https://oneshetland.com/wp-content/uploads/2026/03/Ken-Ludwigs–MORIARTY.webp$$, NULL),
  ($$Soothend Walkers$$, $$Soothend Walkers at Carnegie Hall.$$, timestamp '2026-03-26 14:00:00' at time zone 'Europe/London', timestamp '2026-03-26 15:00:00' at time zone 'Europe/London', $$Carnegie Hall$$, $$Sports & Outdoors$$, $$https://oneshetland.com/wp-content/uploads/2026/03/soothend-walkers-2.webp$$, NULL),
  ($$Shetland Accordion & Fiddle Club$$, $$Shetland Accordion & Fiddle Club at The Royal British Legion Scotland.$$, timestamp '2026-03-26 19:30:00' at time zone 'Europe/London', timestamp '2026-03-26 23:00:00' at time zone 'Europe/London', $$The Royal British Legion Scotland$$, $$Music & Gigs$$, $$https://oneshetland.com/wp-content/uploads/2026/03/shetland-accordion-fiddle-club.webp$$, NULL),
  ($$Wastside Bairns DISCO$$, $$Wastside Bairns DISCO at Bixter Public Hall.$$, timestamp '2026-03-27 18:00:00' at time zone 'Europe/London', timestamp '2026-03-27 21:00:00' at time zone 'Europe/London', $$Bixter Public Hall$$, $$Family & Kids$$, $$https://oneshetland.com/wp-content/uploads/2026/03/wastside-bairns-disco.webp$$, NULL),
  ($$Traditional Session Music Nights$$, $$Traditional Session Music Nights at Vidlin Hall — live music in an intimate island setting.$$, timestamp '2026-03-27 19:00:00' at time zone 'Europe/London', timestamp '2026-03-27 23:45:00' at time zone 'Europe/London', $$Vidlin Hall$$, $$Heritage & Culture$$, $$https://oneshetland.com/wp-content/uploads/2026/02/Traditional-Session-Music-Nights.jpg$$, NULL),
  ($$Quiz Night$$, $$Quiz Night at Gulberwick Hall.$$, timestamp '2026-03-27 19:00:00' at time zone 'Europe/London', timestamp '2026-03-27 23:00:00' at time zone 'Europe/London', $$Gulberwick Hall$$, $$Charity & Community$$, $$https://oneshetland.com/wp-content/uploads/2026/03/gulberwick-hall-quiz-night.png$$, NULL),
  ($$The Royal Scottish Academy at 200: a talk by Sandy Wood, Head of Collections$$, $$The Royal Scottish Academy at 200: a talk by Sandy Wood, Head of Collections at Mareel.$$, timestamp '2026-03-27 19:30:00' at time zone 'Europe/London', timestamp '2026-03-27 21:30:00' at time zone 'Europe/London', $$Mareel - Music -  Cinema and Education Venue$$, $$Heritage & Culture$$, $$https://oneshetland.com/wp-content/uploads/2026/03/the-royal-scottish-academy-at-200-a-talk-by-sandy-wood-head-of-collections.webp$$, NULL),
  ($$Lerwick Lifeboat Coffee Morning$$, $$Lerwick Lifeboat Coffee Morning at Sound Hall, Upper Sound, Lerwick.$$, timestamp '2026-03-28 10:00:00' at time zone 'Europe/London', timestamp '2026-03-28 12:00:00' at time zone 'Europe/London', $$Sound Hall$$, $$Charity & Community$$, $$https://oneshetland.com/wp-content/uploads/2026/03/RNLI-coffee-morning-fundraiser.png$$, NULL),
  ($$Da Muckle Market$$, $$Da Muckle Market at Gulberwick Hall.$$, timestamp '2026-03-28 11:00:00' at time zone 'Europe/London', timestamp '2026-03-28 15:00:00' at time zone 'Europe/London', $$Gulberwick Hall$$, $$Market$$, $$https://oneshetland.com/wp-content/uploads/2026/03/da-muckle-market.webp$$, NULL),
  ($$Country & Western Nights$$, $$Country & Western Nights at Mareel.$$, timestamp '2026-04-03 19:30:00' at time zone 'Europe/London', timestamp '2026-04-03 22:30:00' at time zone 'Europe/London', $$Mareel - Music -  Cinema and Education Venue$$, $$Music & Gigs$$, $$https://oneshetland.com/wp-content/uploads/2026/03/country-western-nights.webp$$, NULL),
  ($$Variety Concert$$, $$Variety Concert at Walls Public Hall.$$, timestamp '2026-04-03 19:30:00' at time zone 'Europe/London', timestamp '2026-04-03 23:00:00' at time zone 'Europe/London', $$Walls Public Hall$$, $$Charity & Community$$, $$https://oneshetland.com/wp-content/uploads/2026/03/variety-concert.webp$$, NULL),
  ($$Easter Egg Hunt$$, $$Easter Egg Hunt at Mid Yell Hall — a family-friendly adventure with clues and surprises.$$, timestamp '2026-04-04 10:00:00' at time zone 'Europe/London', timestamp '2026-04-04 12:00:00' at time zone 'Europe/London', $$Mid Yell Hall$$, $$Family & Kids$$, NULL, NULL),
  ($$Country & Western Nights (matinee)$$, $$Country & Western Nights at Mareel.$$, timestamp '2026-04-04 14:30:00' at time zone 'Europe/London', timestamp '2026-04-04 17:00:00' at time zone 'Europe/London', $$Mareel - Music -  Cinema and Education Venue$$, $$Music & Gigs$$, $$https://oneshetland.com/wp-content/uploads/2026/03/country-western-nights.webp$$, NULL),
  ($$Country & Western Nights (evening)$$, $$Country & Western Nights at Mareel.$$, timestamp '2026-04-04 18:30:00' at time zone 'Europe/London', timestamp '2026-04-04 21:30:00' at time zone 'Europe/London', $$Mareel - Music -  Cinema and Education Venue$$, $$Music & Gigs$$, $$https://oneshetland.com/wp-content/uploads/2026/03/country-western-nights.webp$$, NULL),
  ($$Duck Race$$, $$Duck Race at Bixter Public Hall.$$, timestamp '2026-04-05 14:00:00' at time zone 'Europe/London', timestamp '2026-04-05 16:00:00' at time zone 'Europe/London', $$Bixter Public Hall$$, $$Family & Kids$$, NULL, NULL),
  ($$Mama Terra$$, $$Mama Terra at Mareel.$$, timestamp '2026-04-10 19:30:00' at time zone 'Europe/London', timestamp '2026-04-10 22:30:00' at time zone 'Europe/London', $$Mareel - Music -  Cinema and Education Venue$$, $$Music & Gigs$$, $$https://oneshetland.com/wp-content/uploads/2026/03/mama-terra.webp$$, NULL),
  ($$Book Launch – Death in a Shetland Family$$, $$Book Launch – Death in a Shetland Family at Shetland Library.$$, timestamp '2026-04-16 18:30:00' at time zone 'Europe/London', timestamp '2026-04-16 19:30:00' at time zone 'Europe/London', $$Shetland Library$$, $$Literature$$, $$https://oneshetland.com/wp-content/uploads/2026/03/book-launch-death-in-a-shetland-family.webp$$, NULL),
  ($$Kris Drever with special guest Annie Dressner$$, $$Kris Drever with special guest Annie Dressner at Mareel.$$, timestamp '2026-04-17 19:30:00' at time zone 'Europe/London', timestamp '2026-04-17 22:15:00' at time zone 'Europe/London', $$Mareel - Music -  Cinema and Education Venue$$, $$Music & Gigs$$, $$https://oneshetland.com/wp-content/uploads/2026/03/kris-drever-with-special-guest-annie-dressner.jpg$$, NULL),
  ($$The Taylor Swift Effect$$, $$The Taylor Swift Effect at Mareel.$$, timestamp '2026-04-19 13:00:00' at time zone 'Europe/London', timestamp '2026-04-19 15:00:00' at time zone 'Europe/London', $$Mareel - Music -  Cinema and Education Venue$$, $$Family & Kids$$, $$https://oneshetland.com/wp-content/uploads/2026/03/the-taylor-swift-effect.webp$$, NULL),
  ($$Shetland Young Fiddler of the Year$$, $$Shetland Young Fiddler of the Year.$$, timestamp '2026-04-24 03:00:00' at time zone 'Europe/London', timestamp '2026-04-25 02:59:59' at time zone 'Europe/London', NULL, $$Music & Gigs$$, $$https://oneshetland.com/wp-content/uploads/2026/03/shetland-young-fiddler-of-the-year.webp$$, NULL),
  ($$Shetland Parasport Festival$$, $$Shetland Parasport Festival.$$, timestamp '2026-04-25 09:30:00' at time zone 'Europe/London', timestamp '2026-04-25 16:00:00' at time zone 'Europe/London', NULL, $$Sports & Outdoors$$, NULL, NULL),
  ($$Shetland Folk Festival$$, $$Shetland Folk Festival — one of Shetland’s most anticipated events.$$, timestamp '2026-04-30 03:00:00' at time zone 'Europe/London', timestamp '2026-05-03 23:59:59' at time zone 'Europe/London', NULL, $$Festivals & Celebrations$$, $$https://oneshetland.com/wp-content/uploads/2026/03/shetland-folk-festival.webp$$, NULL),
  ($$Absolute Elvis (Johnny Lee Memphis)$$, $$Absolute Elvis (Johnny Lee Memphis) at Mareel.$$, timestamp '2026-05-15 19:30:00' at time zone 'Europe/London', timestamp '2026-05-15 22:00:00' at time zone 'Europe/London', $$Mareel - Music -  Cinema and Education Venue$$, $$Music & Gigs$$, $$https://oneshetland.com/wp-content/uploads/2026/03/absolute-elvis-johnny-lee-memphis.webp$$, NULL),
  ($$Kenneth Pattengale (of The Milk Carton Kids)$$, $$Kenneth Pattengale (of The Milk Carton Kids) at Mareel.$$, timestamp '2026-05-20 19:30:00' at time zone 'Europe/London', timestamp '2026-05-20 22:15:00' at time zone 'Europe/London', $$Mareel - Music -  Cinema and Education Venue$$, $$Music & Gigs$$, NULL, NULL),
  ($$Tae Sup Wi’ a Fifer$$, $$Tae Sup Wi’ a Fifer at Mareel.$$, timestamp '2026-05-23 19:30:00' at time zone 'Europe/London', timestamp '2026-05-23 22:30:00' at time zone 'Europe/London', $$Mareel - Music -  Cinema and Education Venue$$, $$Heritage & Culture$$, $$https://oneshetland.com/wp-content/uploads/2026/03/tae-sup-wi-a-fifer.jpg$$, NULL),
  ($$Shetland Noir 2026$$, $$Shetland Noir 2026 at Mareel.$$, timestamp '2026-06-11 03:00:00' at time zone 'Europe/London', timestamp '2026-06-14 23:59:59' at time zone 'Europe/London', $$Mareel - Music -  Cinema and Education Venue$$, $$Festivals & Celebrations$$, $$https://oneshetland.com/wp-content/uploads/2026/03/shetland-noir-2026.jpg$$, NULL),
  ($$Shetland Pride Festival$$, $$Shetland Pride Festival.$$, timestamp '2026-06-13 03:00:00' at time zone 'Europe/London', timestamp '2026-06-14 02:59:59' at time zone 'Europe/London', NULL, $$Festivals & Celebrations$$, $$https://oneshetland.com/wp-content/uploads/2026/03/shetland-pride-festival.webp$$, NULL),
  ($$Bergen to Shetland Race 2026$$, $$Bergen to Shetland Race 2026 at Lerwick Port Authority.$$, timestamp '2026-06-16 03:00:00' at time zone 'Europe/London', timestamp '2026-06-21 23:59:59' at time zone 'Europe/London', $$Lerwick Port Authority$$, $$Sports & Outdoors$$, $$https://oneshetland.com/wp-content/uploads/2026/03/bergen-to-shetland-race-2026.jpeg$$, NULL),
  ($$Simmer Dim Rally$$, $$Simmer Dim Rally at Vidlin, Shetland.$$, timestamp '2026-06-18 03:00:00' at time zone 'Europe/London', timestamp '2026-06-21 23:59:59' at time zone 'Europe/London', $$Vidlin$$, $$Sports & Outdoors$$, $$https://oneshetland.com/wp-content/uploads/2026/03/simmer-dim-rally.webp$$, NULL),
  ($$UnstFest$$, $$UnstFest at Unst, Shetland.$$, timestamp '2026-07-20 03:00:00' at time zone 'Europe/London', timestamp '2026-07-26 23:59:59' at time zone 'Europe/London', $$Baltasound Hall$$, $$Festivals & Celebrations$$, $$https://oneshetland.com/wp-content/uploads/2026/03/unstfest.webp$$, NULL),
  ($$Shetland Fiddle Week 2026$$, $$Shetland Fiddle Week 2026 at Islesburgh Community Centre.$$, timestamp '2026-08-03 03:00:00' at time zone 'Europe/London', timestamp '2026-08-08 23:59:59' at time zone 'Europe/London', $$Islesburgh Community Centre$$, $$Heritage & Culture$$, $$https://oneshetland.com/wp-content/uploads/2026/03/shetland-fiddle-week-2026.jpg$$, NULL),
  ($$Cunningsburgh Show 2026$$, $$Cunningsburgh Show 2026 — celebrating Shetland’s agricultural and community traditions.$$, timestamp '2026-08-12 03:00:00' at time zone 'Europe/London', timestamp '2026-08-13 02:59:59' at time zone 'Europe/London', $$Cunningsburgh$$, $$Art & Exhibitions$$, $$https://oneshetland.com/wp-content/uploads/2026/03/cunningsburgh-show-2026.webp$$, NULL),
  ($$Rising North Music Festival$$, $$Rising North Music Festival.$$, timestamp '2026-08-13 03:00:00' at time zone 'Europe/London', timestamp '2026-08-16 23:59:59' at time zone 'Europe/London', NULL, $$Festivals & Celebrations$$, NULL, NULL),
  ($$Norah Howie Psychic Medium$$, $$Norah Howie Psychic Medium at Mareel.$$, timestamp '2026-08-25 19:30:00' at time zone 'Europe/London', timestamp '2026-08-25 21:30:00' at time zone 'Europe/London', $$Mareel - Music -  Cinema and Education Venue$$, $$Theatre$$, $$https://oneshetland.com/wp-content/uploads/2026/03/norah-howie-psychic-medium.webp$$, NULL),
  ($$Fetlar Hall Sunday Teas$$, $$Fetlar Hall Sunday Teas — a much-loved local gathering with home baking and tea.$$, timestamp '2026-08-30 12:00:00' at time zone 'Europe/London', timestamp '2026-08-30 15:00:00' at time zone 'Europe/London', $$Fetlar Hall$$, $$Food & Drink$$, NULL, NULL),
  ($$Shetland Wool Week 2026$$, $$Shetland Wool Week 2026.$$, timestamp '2026-09-27 03:00:00' at time zone 'Europe/London', timestamp '2026-10-03 23:59:59' at time zone 'Europe/London', NULL, $$Art & Exhibitions$$, $$https://oneshetland.com/wp-content/uploads/2026/03/shetland-wool-week-2026.jpg$$, NULL),
  ($$Christopher Macarthur-Boyd: Howling at the Moon$$, $$Christopher Macarthur-Boyd: Howling at the Moon at Mareel.$$, timestamp '2026-10-03 20:00:00' at time zone 'Europe/London', timestamp '2026-10-03 21:40:00' at time zone 'Europe/London', $$Mareel - Music -  Cinema and Education Venue$$, $$Comedy$$, NULL, NULL),
  ($$Shetland Accordion & Fiddle Festival 2026$$, $$Shetland Accordion & Fiddle Festival 2026.$$, timestamp '2026-10-08 03:00:00' at time zone 'Europe/London', timestamp '2026-10-11 23:59:59' at time zone 'Europe/London', NULL, $$Heritage & Culture$$, $$https://oneshetland.com/wp-content/uploads/2026/03/shetland-accordion-fiddle-festival-2026.webp$$, NULL),
  ($$Voe Social Club$$, $$Voe Social Club.$$, timestamp '2026-10-14 10:00:00' at time zone 'Europe/London', timestamp '2026-10-14 12:00:00' at time zone 'Europe/London', $$Voe$$, $$Music & Gigs$$, NULL, NULL),
  ($$Calum MacPhail Live$$, $$Calum MacPhail Live at Mareel.$$, timestamp '2026-10-16 20:00:00' at time zone 'Europe/London', timestamp '2026-10-16 22:00:00' at time zone 'Europe/London', $$Mareel - Music -  Cinema and Education Venue$$, $$Music & Gigs$$, $$https://oneshetland.com/wp-content/uploads/2026/03/calum-macphail-live.jpg$$, NULL),
  ($$Gary Meikle: Yer Maw$$, $$Gary Meikle: Yer Maw at Mareel.$$, timestamp '2026-10-30 19:30:00' at time zone 'Europe/London', timestamp '2026-10-30 21:30:00' at time zone 'Europe/London', $$Mareel - Music -  Cinema and Education Venue$$, $$Comedy$$, NULL, NULL),
  ($$Lerwick Up Helly Aa$$, $$Lerwick Up Helly Aa — Shetland’s world-famous fire festival.$$, timestamp '2027-01-26 03:00:00' at time zone 'Europe/London', timestamp '2027-01-27 02:59:59' at time zone 'Europe/London', $$Lerwick$$, $$Heritage & Culture$$, $$https://oneshetland.com/wp-content/uploads/2025/11/up-helly-aa.webp$$, NULL),
  ($$Lerwick Junior Up Helly Aa$$, $$Lerwick Junior Up Helly Aa at Lower Hillhead, Lerwick.$$, timestamp '2027-01-26 03:00:00' at time zone 'Europe/London', timestamp '2027-01-27 02:59:59' at time zone 'Europe/London', $$Lerwick$$, $$Heritage & Culture$$, $$https://oneshetland.com/wp-content/uploads/2026/03/lerwick-junior-up-helly-aa.jpg$$, NULL)
) as v(title, description, starts_at, ends_at, venue, category, cover_url, price_text)
where not exists (
  select 1 from public.events e
  where e.title = v.title and e.starts_at = v.starts_at
);
