add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_spik_dictionary_fields_v2',
	'title' => 'Spik Dictionary Fields',
	'fields' => array(
		array(
			'key' => 'field_spik_tab_core',
			'label' => 'Core Dictionary',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_alternate_spelling',
			'label' => 'Alternate spelling',
			'name' => 'alternate_spelling',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_stripped_word',
			'label' => 'Stripped word',
			'name' => 'stripped_word',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Normalised helper version of the word for matching/search.',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_first_letter',
			'label' => 'First letter',
			'name' => 'first_letter',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_spik_meaning',
			'label' => 'Spik meaning',
			'name' => 'spik_meaning',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Main dictionary meaning.',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'new_lines' => 'wpautop',
			'rows' => 4,
			'placeholder' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_short_meaning',
			'label' => 'Short meaning',
			'name' => 'short_meaning',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Short gloss for cards, search and game use.',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'new_lines' => 'br',
			'rows' => 3,
			'placeholder' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_example_sentence',
			'label' => 'Example sentence',
			'name' => 'example_sentence',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'new_lines' => 'wpautop',
			'rows' => 4,
			'placeholder' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_spik_tab_classification',
			'label' => 'Classification',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_part_of_speech',
			'label' => 'Part of speech',
			'name' => 'part_of_speech',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'noun' => 'noun',
				'modal verb' => 'modal verb',
				'determiner' => 'determiner',
				'adjective' => 'adjective',
				'verb' => 'verb',
				'adverb' => 'adverb',
				'preposition' => 'preposition',
				'plural noun' => 'plural noun',
				'adjective phrase' => 'adjective phrase',
				'adjectival phrase' => 'adjectival phrase',
				'auxiliary verb' => 'auxiliary verb',
				'pronoun' => 'pronoun',
				'interjection' => 'interjection',
				'conjunction' => 'conjunction',
				'adjective/adverb' => 'adjective/adverb',
				'relative pronoun' => 'relative pronoun',
				'prepositional phrase' => 'prepositional phrase',
				'determiner/pronoun' => 'determiner/pronoun',
				'adverbial phrase' => 'adverbial phrase',
				'intransitive verb' => 'intransitive verb',
				'verb phrase' => 'verb phrase',
				'noun phrase' => 'noun phrase',
				'transitive verb' => 'transitive verb',
				'phrasal verb' => 'phrasal verb',
				'unknown' => 'unknown',
				'past participle' => 'past participle',
				'definite article' => 'definite article',
				'demonstrative determiner/pronoun' => 'demonstrative determiner/pronoun',
				'compound noun' => 'compound noun',
				'personal pronoun' => 'personal pronoun',
				'possessive determiner' => 'possessive determiner',
				'possessive pronoun' => 'possessive pronoun',
				'modal auxiliary phrase' => 'modal auxiliary phrase',
				'demonstrative' => 'demonstrative',
				'reflexive pronoun' => 'reflexive pronoun',
				'cardinal numeral' => 'cardinal numeral',
				'idiomatic noun phrase' => 'idiomatic noun phrase',
				'conjunctive adverb' => 'conjunctive adverb',
				'negative particle' => 'negative particle',
				'indefinite pronoun' => 'indefinite pronoun',
				'auxiliary' => 'auxiliary',
				'idiomatic adverbial phrase' => 'idiomatic adverbial phrase',
				'determiner/adjective' => 'determiner/adjective',
				'idiomatic phrase' => 'idiomatic phrase',
				'indefinite numeral' => 'indefinite numeral',
				'numeral' => 'numeral',
				'phrase' => 'phrase',
				'interrogative pronoun' => 'interrogative pronoun',
				'conjunction/adverb' => 'conjunction/adverb',
				'interrogative determiner' => 'interrogative determiner',
			),
			'default_value' => false,
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'create_options' => 0,
			'save_options' => 0,
		),
		array(
			'key' => 'field_category',
			'label' => 'Category',
			'name' => 'category',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'emotion' => 'emotion',
				'nature' => 'nature',
				'sea' => 'sea',
				'object' => 'object',
				'action' => 'action',
				'animals' => 'animals',
				'quality' => 'quality',
				'people' => 'people',
				'clothing' => 'clothing',
				'food' => 'food',
				'body' => 'body',
				'home' => 'home',
				'place' => 'place',
				'work' => 'work',
				'weather' => 'weather',
				'time' => 'time',
			),
			'default_value' => false,
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'create_options' => 0,
			'save_options' => 0,
		),
		array(
			'key' => 'field_usage_level',
			'label' => 'Usage level',
			'name' => 'usage_level',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '34',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'common' => 'common',
				'known' => 'known',
				'less common' => 'less common',
				'rare' => 'rare',
				'uncommon' => 'uncommon',
			),
			'default_value' => false,
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'create_options' => 0,
			'save_options' => 0,
		),
		array(
			'key' => 'field_era',
			'label' => 'Era',
			'name' => 'era',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'older' => 'older',
				'current' => 'current',
				'archaic' => 'archaic',
				'neutral' => 'neutral',
			),
			'default_value' => false,
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'create_options' => 0,
			'save_options' => 0,
		),
		array(
			'key' => 'field_tone',
			'label' => 'Tone',
			'name' => 'tone',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'neutral' => 'neutral',
				'harsh' => 'harsh',
				'insult' => 'insult',
				'humorous' => 'humorous',
				'affectionate' => 'affectionate',
				'warm' => 'warm',
			),
			'default_value' => false,
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'create_options' => 0,
			'save_options' => 0,
		),
		array(
			'key' => 'field_origin',
			'label' => 'Origin',
			'name' => 'origin',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '34',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'old norse' => 'Old Norse',
				'scots' => 'Scots',
				'unknown' => 'Unknown',
			),
			'default_value' => false,
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'create_options' => 0,
			'save_options' => 0,
		),
		array(
			'key' => 'field_verification',
			'label' => 'Verification',
			'name' => 'verification',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'initial research' => 'Initial Research',
				'updated' => 'Updated',
				'contributor updated' => 'Contributor Updated',
			),
			'default_value' => false,
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'create_options' => 0,
			'save_options' => 0,
		),
		array(
			'key' => 'field_word_status',
			'label' => 'Word status',
			'name' => 'word_status',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'draft' => 'draft',
				'review' => 'review',
				'approved' => 'approved',
				'published' => 'published',
				'archived' => 'archived',
				'duplicate' => 'duplicate',
				'rejected' => 'rejected',
			),
			'default_value' => false,
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'create_options' => 0,
			'save_options' => 0,
		),
		array(
			'key' => 'field_spik_tab_language_search',
			'label' => 'Language & Search',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_pronunciation',
			'label' => 'Pronunciation',
			'name' => 'pronunciation',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_phonetic_search',
			'label' => 'Phonetic search',
			'name' => 'phonetic_search',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_number_letters',
			'label' => 'Number letters',
			'name' => 'number_letters',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '34',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => 0,
			'step' => 1,
			'placeholder' => '',
			'max' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_url_slug',
			'label' => 'URL slug',
			'name' => 'url_slug',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_forwirds_id',
			'label' => 'ForWirds ID',
			'name' => 'forwirds_id',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_forwirds_meaning',
			'label' => 'ForWirds meaning',
			'name' => 'forwirds_meaning',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'new_lines' => 'br',
			'rows' => 3,
			'placeholder' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_spik_tab_audio',
			'label' => 'Audio',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_word_audio_url',
			'label' => 'Word audio URL',
			'name' => 'word_audio_url',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_sentence_audio_url',
			'label' => 'Sentence audio URL',
			'name' => 'sentence_audio_url',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_audio_filename',
			'label' => 'Audio filename',
			'name' => 'audio_filename',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_audio_script',
			'label' => 'Audio script',
			'name' => 'audio_script',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'new_lines' => 'br',
			'rows' => 4,
			'placeholder' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_spik_tab_game',
			'label' => 'Wirdil',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_wirdil_hint_1',
			'label' => 'Wirdil Hint 1',
			'name' => 'wirdil_hint_1',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_wirdil_hint_2',
			'label' => 'Wirdil Hint 2',
			'name' => 'wirdil_hint_2',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_wirdil_hint_3',
			'label' => 'Wirdil Hint 3',
			'name' => 'wirdil_hint_3',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '34',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_spik_tab_contributor',
			'label' => 'Contributor & Notes',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_contributor_name',
			'label' => 'Contributor name',
			'name' => 'contributor_name',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_contributor_email',
			'label' => 'Contributor email',
			'name' => 'contributor_email',
			'aria-label' => '',
			'type' => 'email',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_speaker_area',
			'label' => 'Speaker area',
			'name' => 'speaker_area',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '34',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_notes',
			'label' => 'Notes',
			'name' => 'notes',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'new_lines' => 'wpautop',
			'rows' => 4,
			'placeholder' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_spik_tab_workflow',
			'label' => 'Workflow',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_submission_type',
			'label' => 'Submission type',
			'name' => 'submission_type',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'manual' => 'manual',
				'import' => 'import',
				'community' => 'community',
				'expert' => 'expert',
				'ai' => 'ai',
				'legacy' => 'legacy',
			),
			'default_value' => false,
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'create_options' => 0,
			'save_options' => 0,
		),
		array(
			'key' => 'field_consent_given',
			'label' => 'Consent given',
			'name' => 'consent_given',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Yes',
			'ui_off_text' => 'No',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'spik_word',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'discussion',
		3 => 'comments',
		4 => 'slug',
		5 => 'author',
		6 => 'format',
		7 => 'page_attributes',
		8 => 'featured_image',
		9 => 'categories',
		10 => 'tags',
	),
	'active' => true,
	'description' => 'Structured field group for the Spik dictionary CPT.',
	'show_in_rest' => 1,
	'display_title' => '',
) );
} );

