-- ── 036_shetland_places_corrections.sql ───────────────────────────────────
--
-- Apply verified coordinates from supabase/map-locations.xlsx
-- (verifier filled in `verified_lat` + `verified_lng`).
--
-- Matching is by region + (name OR alt_name), using the name as it appeared
-- in the verifier CSV. Where the verifier renamed a place in the xlsx
-- (e.g. "Sneug" stayed because unverified, "Hammar" → "Hamar"), we also
-- UPDATE the primary name to the verifier preferred spelling.
-- ────────────────────────────────────────────────────────────────────────────
-- 72 verified UPDATEs applied (of which 7 also renamed)
-- 2 marked inactive ("does not exist")
-- 2 skipped — verifier coord outside Shetland bounding box
-- 17 unverified (flagged in notes column)


UPDATE public.game_shetland_places SET notes = COALESCE(notes,'') || ' [unverified - best-guess coords]' WHERE region = 'south mainland' AND ('Stove' = name OR 'Stove' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 59.931110, lng = -1.302720, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'south mainland' AND ('Skelberry' = name OR 'Skelberry' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.005262, lng = -1.324158, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'south mainland' AND ('Maywick' = name OR 'Maywick' = ANY(alt_names));
-- [SKIP] Sandwick Bay (south mainland) — verifier coord (58.78547, -2.98442) outside Shetland. Needs re-check.
UPDATE public.game_shetland_places SET lat = 59.939683, lng = -1.324832, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'south mainland' AND ('Spiggie Hotel' = name OR 'Spiggie Hotel' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 59.865380, lng = -1.295870, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'south mainland' AND ('West Voe of Sumburgh' = name OR 'West Voe of Sumburgh' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 59.884730, lng = -1.292610, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'south mainland' AND ('Pool of Virkie' = name OR 'Pool of Virkie' = ANY(alt_names));
UPDATE public.game_shetland_places SET is_active = FALSE, notes = COALESCE(notes,'') || ' [does not exist - verifier]' WHERE region = 'south mainland' AND ('Scousburgh Hill' = name OR 'Scousburgh Hill' = ANY(alt_names));
UPDATE public.game_shetland_places SET is_active = FALSE, notes = COALESCE(notes,'') || ' [does not exist - verifier]' WHERE region = 'south mainland' AND ('Catpund' = name OR 'Catpund' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.276370, lng = -1.203840, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'central' AND ('Catfirth' = name OR 'Catfirth' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.293974, lng = -1.271635, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'central' AND ('Kergord' = name OR 'Kergord' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.064262, lng = -1.324947, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'central' AND ('Houss' = name OR 'Houss' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.146550, lng = -1.170390, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'central' AND ('Sound (Lerwick)' = name OR 'Sound (Lerwick)' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.133235, lng = -1.260467, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'central' AND ('Easterhoull' = name OR 'Easterhoull' = ANY(alt_names));
UPDATE public.game_shetland_places SET name = 'South Havra', lat = 60.025560, lng = -1.355480, notes = COALESCE(notes,'') || ' [verified+renamed ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'central' AND ('Havra' = name OR 'Havra' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.146850, lng = -1.360330, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'central' AND ('Hildasay' = name OR 'Hildasay' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.504860, lng = -1.569670, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'central' AND ('Hamna Voe' = name OR 'Hamna Voe' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.068050, lng = -1.305060, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'central' AND ('Cliff Sound' = name OR 'Cliff Sound' = ANY(alt_names));
UPDATE public.game_shetland_places SET notes = COALESCE(notes,'') || ' [unverified - best-guess coords]' WHERE region = 'central' AND ('Catfirth Voe' = name OR 'Catfirth Voe' = ANY(alt_names));
UPDATE public.game_shetland_places SET notes = COALESCE(notes,'') || ' [unverified - best-guess coords]' WHERE region = 'central' AND ('Loch of Hellier' = name OR 'Loch of Hellier' = ANY(alt_names));
UPDATE public.game_shetland_places SET notes = COALESCE(notes,'') || ' [unverified - best-guess coords]' WHERE region = 'central' AND ('Loch of Vatsaund' = name OR 'Loch of Vatsaund' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.702923, lng = -0.961282, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'central' AND ('Loch of Snabrough' = name OR 'Loch of Snabrough' = ANY(alt_names));
-- [SKIP] Black Loch (central) — verifier coord (-1.252, 60.7368) outside Shetland. Needs re-check.
UPDATE public.game_shetland_places SET lat = 60.141060, lng = -1.166740, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'central' AND ('Sands of Sound' = name OR 'Sands of Sound' = ANY(alt_names));
UPDATE public.game_shetland_places SET notes = COALESCE(notes,'') || ' [unverified - best-guess coords]' WHERE region = 'central' AND ('Eswick Beach' = name OR 'Eswick Beach' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.039911, lng = -1.290759, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'central' AND ('Royl Field' = name OR 'Royl Field' = ANY(alt_names));
UPDATE public.game_shetland_places SET notes = COALESCE(notes,'') || ' [unverified - best-guess coords]' WHERE region = 'central' AND ('Tingaholm' = name OR 'Tingaholm' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.170034, lng = -1.164819, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'central' AND ('Bod of Gremista' = name OR 'Bod of Gremista' = ANY(alt_names));
UPDATE public.game_shetland_places SET notes = COALESCE(notes,'') || ' [unverified - best-guess coords]' WHERE region = 'central' AND ('The Lodberries' = name OR 'The Lodberries' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.152063, lng = -1.136286, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'central' AND ('Twageos' = name OR 'Twageos' = ANY(alt_names));
UPDATE public.game_shetland_places SET notes = COALESCE(notes,'') || ' [unverified - best-guess coords]' WHERE region = 'central' AND ('Catfirth Seaplane Base' = name OR 'Catfirth Seaplane Base' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.060090, lng = -1.347010, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'central' AND ('Banna Minn' = name OR 'Banna Minn' = ANY(alt_names));
UPDATE public.game_shetland_places SET name = 'Hill of Voxter', lat = 60.328438, lng = -1.348164, notes = COALESCE(notes,'') || ' [verified+renamed ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'north mainland' AND ('Voxter' = name OR 'Voxter' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.628500, lng = -0.933670, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'north mainland' AND ('Hamarsness' = name OR 'Hamarsness' = ANY(alt_names));
UPDATE public.game_shetland_places SET notes = COALESCE(notes,'') || ' [unverified - best-guess coords]' WHERE region = 'north mainland' AND ('Heylor' = name OR 'Heylor' = ANY(alt_names));
UPDATE public.game_shetland_places SET notes = COALESCE(notes,'') || ' [unverified - best-guess coords]' WHERE region = 'north mainland' AND ('Swarbacks Minn' = name OR 'Swarbacks Minn' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.606100, lng = -1.340030, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'north mainland' AND ('Sand Voe' = name OR 'Sand Voe' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.381760, lng = -1.399810, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'north mainland' AND ('Roe Sound' = name OR 'Roe Sound' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.157470, lng = -1.281340, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'north mainland' AND ('Loch of Houlland' = name OR 'Loch of Houlland' = ANY(alt_names));
UPDATE public.game_shetland_places SET name = 'Otter Holm', lat = 60.480904, lng = -1.584048, notes = COALESCE(notes,'') || ' [verified+renamed ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'north mainland' AND ('Otter''s Geo' = name OR 'Otter''s Geo' = ANY(alt_names));
UPDATE public.game_shetland_places SET notes = COALESCE(notes,'') || ' [unverified - best-guess coords]' WHERE region = 'north mainland' AND ('Da Drongs' = name OR 'Da Drongs' = ANY(alt_names));
UPDATE public.game_shetland_places SET notes = COALESCE(notes,'') || ' [unverified - best-guess coords]' WHERE region = 'north mainland' AND ('Hellisgill' = name OR 'Hellisgill' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.483890, lng = -1.578810, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'north mainland' AND ('Tangwick Haa' = name OR 'Tangwick Haa' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.516460, lng = -1.292180, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'north mainland' AND ('Lamba' = name OR 'Lamba' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.468540, lng = -1.153050, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'north mainland' AND ('Samphrey' = name OR 'Samphrey' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.370170, lng = -1.423930, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'north mainland' AND ('Muckle Roe' = name OR 'Muckle Roe' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.181140, lng = -1.418610, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'west mainland' AND ('Reawick' = name OR 'Reawick' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.220380, lng = -1.356120, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'west mainland' AND ('Sandsound' = name OR 'Sandsound' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.253870, lng = -1.400240, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'west mainland' AND ('Bixter' = name OR 'Bixter' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.264860, lng = -1.411360, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'west mainland' AND ('Twatt' = name OR 'Twatt' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.242880, lng = -1.348920, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'west mainland' AND ('Tresta (Mainland)' = name OR 'Tresta (Mainland)' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.201020, lng = -1.587700, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'west mainland' AND ('Vaila' = name OR 'Vaila' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.239820, lng = -1.685180, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'west mainland' AND ('Loch of Watsness' = name OR 'Loch of Watsness' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.235439, lng = -1.486539, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'west mainland' AND ('Stanydale Temple' = name OR 'Stanydale Temple' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.585370, lng = -1.021900, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'yell' AND ('Vatsetter' = name OR 'Vatsetter' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.651295, lng = -1.038036, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'yell' AND ('Cunnister' = name OR 'Cunnister' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.569680, lng = -0.896420, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'yell' AND ('Mailand' = name OR 'Mailand' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.563020, lng = -1.028770, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'yell' AND ('Aywick' = name OR 'Aywick' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.554330, lng = -1.049540, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'yell' AND ('Otterswick' = name OR 'Otterswick' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.661150, lng = -1.047990, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'yell' AND ('Sellafirth' = name OR 'Sellafirth' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.575670, lng = -1.183780, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'yell' AND ('West Sandwick' = name OR 'West Sandwick' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.722070, lng = -1.071850, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'yell' AND ('Gloup' = name OR 'Gloup' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.495070, lng = -1.190130, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'yell' AND ('Bigga' = name OR 'Bigga' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.666370, lng = -0.980440, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'yell' AND ('Linga (Yell)' = name OR 'Linga (Yell)' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.608790, lng = -0.992200, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'yell' AND ('Hascosay' = name OR 'Hascosay' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.496050, lng = -1.045330, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'yell' AND ('Burra Voe (Yell)' = name OR 'Burra Voe (Yell)' = ANY(alt_names));
UPDATE public.game_shetland_places SET name = 'Loch of Windhouse', lat = 60.626339, lng = -1.094835, notes = COALESCE(notes,'') || ' [verified+renamed ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'yell' AND ('Loch of Cunnister' = name OR 'Loch of Cunnister' = ANY(alt_names));
UPDATE public.game_shetland_places SET name = 'Hamar', lat = 60.468200, lng = -1.438050, notes = COALESCE(notes,'') || ' [verified+renamed ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'unst' AND ('Hammar' = name OR 'Hammar' = ANY(alt_names));
UPDATE public.game_shetland_places SET notes = COALESCE(notes,'') || ' [unverified - best-guess coords]' WHERE region = 'unst' AND ('Caddafield' = name OR 'Caddafield' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.801480, lng = -0.878390, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'unst' AND ('Burrafirth' = name OR 'Burrafirth' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.669730, lng = -0.893070, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'unst' AND ('Uyea' = name OR 'Uyea' = ANY(alt_names));
UPDATE public.game_shetland_places SET notes = COALESCE(notes,'') || ' [unverified - best-guess coords]' WHERE region = 'unst' AND ('Mu Ness' = name OR 'Mu Ness' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.815980, lng = -0.797410, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'unst' AND ('Lamba Ness' = name OR 'Lamba Ness' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.710768, lng = -1.125774, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'unst' AND ('Burgi Geos' = name OR 'Burgi Geos' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.727972, lng = -0.873241, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'unst' AND ('Hill of Colvadale' = name OR 'Hill of Colvadale' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.706278, lng = -0.951455, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'unst' AND ('Bordastubble' = name OR 'Bordastubble' = ANY(alt_names));
UPDATE public.game_shetland_places SET name = 'West Loch of Skaw', lat = 60.374704, lng = -0.950253, notes = COALESCE(notes,'') || ' [verified+renamed ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'unst' AND ('Loch of Skaw' = name OR 'Loch of Skaw' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.592780, lng = -0.885090, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'fetlar' AND ('Tresta (Fetlar)' = name OR 'Tresta (Fetlar)' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.242460, lng = -1.361162, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'fetlar' AND ('Tresta Voe' = name OR 'Tresta Voe' = ANY(alt_names));
UPDATE public.game_shetland_places SET notes = COALESCE(notes,'') || ' [unverified - best-guess coords]' WHERE region = 'fetlar' AND ('Tresta Beach' = name OR 'Tresta Beach' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.583340, lng = -0.863800, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'fetlar' AND ('Wick of Tresta' = name OR 'Wick of Tresta' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.347680, lng = -1.011770, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'whalsay' AND ('Hamister' = name OR 'Hamister' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.356720, lng = -0.959500, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'whalsay' AND ('Isbister (Whalsay)' = name OR 'Isbister (Whalsay)' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.377130, lng = -0.931610, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'whalsay' AND ('Skaw (Whalsay)' = name OR 'Skaw (Whalsay)' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.426920, lng = -0.749900, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'out skerries' AND ('Bruray' = name OR 'Bruray' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.420290, lng = -0.771100, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'out skerries' AND ('Housay' = name OR 'Housay' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.424604, lng = -0.726975, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'out skerries' AND ('Bound Skerry' = name OR 'Bound Skerry' = ANY(alt_names));
UPDATE public.game_shetland_places SET name = 'The Noup', lat = 60.121710, lng = -2.083630, notes = COALESCE(notes,'') || ' [verified+renamed ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'foula' AND ('Kame of Foula' = name OR 'Kame of Foula' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 60.140164, lng = -2.095934, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'foula' AND ('Snolda' = name OR 'Snolda' = ANY(alt_names));
UPDATE public.game_shetland_places SET notes = COALESCE(notes,'') || ' [unverified - best-guess coords]' WHERE region = 'foula' AND ('Sneug' = name OR 'Sneug' = ANY(alt_names));
UPDATE public.game_shetland_places SET notes = COALESCE(notes,'') || ' [unverified - best-guess coords]' WHERE region = 'foula' AND ('Lyrawick' = name OR 'Lyrawick' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 59.524650, lng = -1.611568, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'fair isle' AND ('Sheep Rock' = name OR 'Sheep Rock' = ANY(alt_names));
UPDATE public.game_shetland_places SET lat = 59.545870, lng = -1.632540, notes = COALESCE(notes,'') || ' [verified ' || to_char(NOW(),'YYYY-MM-DD') || ']' WHERE region = 'fair isle' AND ('Ward Hill (Fair Isle)' = name OR 'Ward Hill (Fair Isle)' = ANY(alt_names));
